### ISSUE TITLE
address format

### ISSUE THREAD

**Issue by dominictarr** [dominictarr/multiserver#1]
Need to figure out an address format.

I'm thinking that something like
`(type(:args)?)(,type(:args)?)*`

where `,` is a separator, `type` is a protocol name (`ws` or `net` or `utp` etc) `args` is whatever information `type` needs (optional - for example gzip doesn't need args)

ipfs uses `/` like a unix path, but I think this is ambigious because you have to know how many arguments a type takes to be able to parse it! That is especially bad for an upgradable system where you may see a descriptor for a thing that you don't support yet, and won't know what it means. It may mean you'll need to do IO while parsing.

instead better to use a different seperator, and allow protocols to format their args however they need, (provided any internal separators are escaped)

'|' would be nice, because it's a lot like piping, but `,' means you couldn't need to escape it on the terminal.

**Comment by dominictarr** [comment]
@clehner what do you think?

**Comment by clehner** [comment]
Sounds good

**Comment by dominictarr** [comment]
note: we could also hook into the mulitserver addresses to allow users with higher privacy requirements to say things like "only replicate my data over local networks" or "only over tor", etc,
or "not over these protocols which I consider weak" etc

**Comment by dominictarr** [comment]
made this: https://github.com/dominictarr/separator-escape

could use `\` as escape, which is familiar, but since other things use `\` too you have to escape the escapes which is confusing! the separator isn't a problem.
